export const SpecialItem = { // may need a 0 before each single character prop
  "0": "None",
  "1": "CharonObal",
  "2": "HedgehogCurse",
  "3": "HyperionRing",
  "4": "HermesBoots",
  "5": "HeliosBlessing",
  "6": "CalypsosCompass",
  "8": "NerdyGlasses",
  "9": "Khidr's Obol",
  "10": "Alexander's Obol",
  "11": "Ponce de Leon's Obol",
  "12": "Herodotus's Obol",
  "13": "Traitor's Obol"
};

export const SpellType = { // may need a 0 before each single character prop
  "0": "None",
  "1": "Dagger",
  "2": "Axe",
  "3": "TimeBomb",
  "4": "TimeStop",
  "5": "Crow Storm",
  "6": "Translocator",
  "7": "Displacer", // (teleport)
  "8": "Chakram",
  "9": "Scythe",
  "10": "Blade Wall",
  "11": "Flame Shield",
  "12": "Conflux",
  "13": "DragonFire",
  "14": "Traitor Daggers",
  "15": "Dragon fire" // (big, fast)
};

export const ClassType = { // may need a 0 before each single character prop
  "0": "Knight",
  "1": "Mage",
  "2": "Barbarian",
  "3": "Knave",
  "4": "Shinobi",
  "5": "Miner",
  "6": "Spellthief",
  "7": "Lich",
  "8": "Paladin",
  "9": "Archmage",
  "10": "Barbarian King",
  "11": "Assassin",
  "12": "Hokage",
  "13": "Spelunker",
  "14": "SpellSword",
  "15": "Lich King",
  "16": "Dragon",
  "17": "Traitor"
};

export const Traits = {
  "0": "None",
  "1": "ColorBlind",
  "2": "Gay",
  "3": "NearSighted",
  "4": "FarSighted",
  "5": "Dyslexia",
  "6": "Gigantism",
  "7": "Dwarfism",
  "8": "Baldness",
  "9": "Endomorph",
  "10": "Ectomorph",
  "11": "Alzheimers",
  "12": "Dextrocardia",
  "13": "Tourettes",
  "14": "Hyperactive",
  "15": "OCD",
  "16": "Hypergonadism",
  "17": "Hypogonadism",
  "18": "StereoBlind",
  "19": "IBS",
  "20": "Vertigo",
  "21": "TunnelVision",
  "22": "Ambilevous",
  "23": "PAD",
  "24": "Alektorophobia",
  "25": "Hypochondriac",
  "26": "Dementia",
  "27": "Hypermobility",
  "28": "EideticMemory",
  "29": "Nostalgic",
  "30": "CIP",
  "31": "Savant",
  "32": "The One",
  "33": "Clumsy",
  "34": "EHS",
  "35": "Glaucoma",
  "Adopted": 100 // might be "100": "Adopted" or "256": "Adopted" or "Adopted": 256
};